### ISSUE TITLE
Built in method to tell remaining time on a Signal

### ISSUE THREAD

**Issue by sanbox-irl** [Ralith/oddio#42]
I'm designing some UI widgets which should provide a track to show currently playing audio. It needs to know how much time is remaining within the track to show the user how far into the track we currently are.

Right now, it isn't possible to access that behavior on `FramesSignal` directly.

I spoke to Ralith in the Gamedev discord group, and he posted the following:

```
rolling your own signal is the proper way to get arbitrary feedback in general; I'm not necessarily opposed to baking this particular feature into FramesSignal though
```

I'd be in support of baking that feature in. I wouldn't mind providing that PR but I'm reticent to commit any serious code to a codebase I have only a trivial understanding of. If you posted some guidance, I'd give it a go, but I'd also understand that for something like this, doing it yourself might be preferable. Either way, thanks for all the hard work

**Comment by Ralith** [comment]
This could actually be a great learning exercise to explore how controls work. For a reference, you can look at `Gain` and see how an `AtomicU32` is used to share state between `GainControl` and the `Signal` impl. Implementing playback position feedback for `FramesSignal` would then be a matter of replacing the current `t: Cell<f64>` with an `AtomicU64`, and sampling its value in a control struct, using a similar pattern of conversion to/from bits on both sides as needed.

Care should be taken not to confuse the specific case of `FramesSignal`, which can easily communicate a meaningful cursor, with the more general `Signal::remaining` getter, which would require a different approach to expose and is less obviously useful to external code.

**Comment by sanbox-irl** [comment]
going to take this then! Since it's Sunday, and I can't get away with doing this at work, probably won't be till next weekend that I have a pr for it. thanks for the direction!

**Comment by sanbox-irl** [comment]
just pr https://github.com/Ralith/oddio/pull/47

**Comment by Ralith** [comment]
#47 was merged, so I think this is resolved.
