### ISSUE TITLE
Configure Gain smoothing speed

### ISSUE THREAD

**Issue by sanbox-irl** [Ralith/oddio#43]
Right now, Gain smoothing speed is set to `0.1` as a const. It would be nice to configure that as a user.

**Comment by DasEtwas** [comment]
I would prefer the `set_gain` function to take a second argument for this speed.

**Comment by Ralith** [comment]
This would be pretty simple, but out of curiosity, what's the motivation? The current behavior only uses a nonzero smoothing period for the sake of avoiding pops. A period large enough to be easily noticable might want to take different approaches, e.g. interpolating in logarithmic space for perceptual linearity, which is more expensive.

**Comment by mooman219** [comment]
Any definition works for me. I assumed the naïve implementation of a hypothetical `set_smooth_interval ` to be:
```
Time             0s    1s    1s    2s  etc
Target Volume  10.0  10.0  10.0  10.0  etc
Current Volume  0.0   5.0   5.0   5.5  etc
Vol per second  5.0   5.0   0.5   0.5  etc
Interval         2s    2s   10s   10s  etc
```
