### ISSUE TITLE
FixedGain that implements Seek

### ISSUE THREAD

**Issue by kettle11** [Ralith/oddio#79]
A `FixedGain` or (`StaticGain`?) signal is useful for cases where one wants to set how loud something is when it starts playing, but never adjust the loudness while it's playing. This allows implementing `Seek` which avoids needing a buffer for spatialization.

Here's a version I've implemented outside `oddio`:

```rust
use oddio::Frame;

pub struct FixedGain<T> {
    gain: f32,
    inner: T,
}

impl<T> FixedGain<T> {
    pub fn new(signal: T, gain: f32) -> Self {
        Self {
            gain,
            inner: signal,
        }
    }
}

impl<T: oddio::Signal> oddio::Signal for FixedGain<T>
where
    T::Frame: oddio::Frame,
{
    type Frame = T::Frame;

    fn sample(&self, interval: f32, out: &mut [Self::Frame]) {
        self.inner.sample(interval, out);
        for frame in out {
            for v in frame.channels_mut() {
                *v *= self.gain
            }
        }
    }
}

impl<T> oddio::Seek for FixedGain<T>
where
    T: oddio::Signal + oddio::Seek,
    T::Frame: Frame,
{
    fn seek(&self, seconds: f32) {
        self.inner.seek(seconds);
    }
}
```

**Comment by Ralith** [comment]
Per sidechannel discussion, I'd like to get more input on use cases for this. Experience so far is that it is sufficient to amplify audio to the desired level once when it's loaded, which requires no changes in oddio and saves some CPU besides.

**Comment by Ralith** [comment]
This was implemented in https://github.com/Ralith/oddio/pull/82. I forget what my line of reasoning was, but it's there now! Maybe if you wanted to play the same `Frames` at a variety of different volumes?
