### ISSUE TITLE
How to use Cycle to loop a sound?

### ISSUE THREAD

**Issue by Nazariglez** [Ralith/oddio#84]
Sorry to add this as an issue, I did not find another way to ask. I'm adding audio support for [notan](https://github.com/Nazariglez/notan) and I am doing some research and tests with oddio. 

I'll implement audio using oddio+symphonia, this combo does all that I need. I was just wondering how to use Cycle to repeat audio I tried to use it as a part of the AudioHandle type but without success, I am not sure how can I chain this type and how to control it later.

Any hint or example will be awesome. Thanks!

**Comment by Ralith** [comment]
Use `Cycle<Sample>` just like you would `FramesSignal<Sample>`. Note that it's not a filter (so you can't wrap it around another signal), and it doesn't expose any controls.

If you still have trouble, please post exact code and errors.

**Comment by Nazariglez** [comment]
Got it, it works like a charm! Thanks

I would like to ask you one last question, there is a way to check if a sound is stopped or paused without a mutable reference? I'm doing [this](https://github.com/Nazariglez/notan/blob/f/aud/crates/notan_oddio/src/backend.rs#L177) using control, and while I don't have any issue with the method been mutable I think that it makes sense to be immutable if possible. But the control method is mutable.

**Comment by Ralith** [comment]
oddio is designed to allow controllable signals to employ SPSC inter-thread communications, which allow various things to be much cheaper and simpler than they might otherwise be, particularly due to the requirement that the real-time audio thread never make a call that might yield control like an alloc, free, or mutex-guarded operation. There's no special case for exemptions to this pattern, but I'd be willing to review design proposals to handle this.

**Comment by Ralith** [comment]
Alternatively, you could just put your handle inside a `RefCell` or similar.

**Comment by Ralith** [comment]
As a side note, you could avoid a lot of redundant matching with a pattern like

```rust
impl AudioHandle {
    fn as_stop(&mut self) -> &mut Stop<dyn Any> { match self { ... } }
}
```

**Comment by Nazariglez** [comment]
> There's no special case for exemptions to this pattern, but I'd be willing to review design proposals to handle this.

I don't have enough expertise (as you can imagine with my simple questions) about how this lib works yet. So I don't feel qualified to do any change on it. But I have a lot of plans to keep extending the use of the oddio backend in my lib, like spatial emitters, or creating music/sounds with it, I hope to learn enough about oddio to be able to contribute it back soon.

I'll keep the mutable reference for now. Also thanks for your "side note" change made.

Btw, I would like to say thank you for your work. I'm also using hecs for a game. I checked quinn, and now oddio. Any crate that comes from you seems to be a high-quality work. And I learn a lot reading internals of them (even though sometimes I don't understand quite well how they do things). 

Thank you so much for sharing.

**Comment by Ralith** [comment]
No problem! I'm glad my libs have been helpful.
