### ISSUE TITLE
Migration from 0.5 to 0.6 Gain can't set initial volume

### ISSUE THREAD

**Issue by Nazariglez** [Ralith/oddio#93]
Hello!

I am migrating from 0.5 to 0.6 and I saw that `Gain` doesn't allow anymore to set the initial volume, to do that I should use `FixedGain` but then it seems that `GainControl` cannot be used in the same way. Is there a way to set the volume _before_ it starts playing and allows to change it after by the user? 

This is the code I want to migrate: https://github.com/Nazariglez/notan/blob/f/prepare0.7.0/crates/notan_oddio/src/backend.rs#L290

And [this is an example](https://nazariglez.github.io/notan-web/examples/audio_basic.html) of how it works now using 0.5.0. You can set the volume before clicking pause and it will start at that level. 

I would appreciate any hint. Thanks

**Comment by Ralith** [comment]
Looks like that case isn't covered by the current API. https://github.com/Ralith/oddio/pull/94 should address that.

**Comment by Ralith** [comment]
Released in 0.6.1.

**Comment by Nazariglez** [comment]
That was fast, thanks!

Though I notice two things now, the first one is that `-60.0` dbs is not "silence" anymore, my `set_volume` function that maps `0-1` to `-60-0` has sound no matter if I pass `0.0` as volume. 

Another thing is that no matter the volume I pass (could be 0.0 or 0.5 whatever) before playing the sound, the first second* (is less than a second) you hear is always at maximum volume and then starts to fade fast. 

Maybe something that I do wrong?

**Comment by Ralith** [comment]
> Though I notice two things now, the first one is that -60.0 dbs is not "silence" anymore

Pure silence is unrepresentable in decibels, but somewhere between -60 and -90 is inaudible in most listening environments. Zero decibels is no change, not silence.

> maximum volume and then starts to fade fast.

Whoops, that's an API limitation. Will fix.

**Comment by Ralith** [comment]
0.6.2 adds dedicated setters on `Gain` that aren't subject to smoothing.

**Comment by Nazariglez** [comment]
Works like a charm! 

Thank you so much for the help, the time, and the work.
